### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by stychu** [diegohaz/rest#156] opened 2018-03-10 17:53 UTC
Im looking for the rest api cli like this but unfortunantely this one is not working I think. You should update the video. I managed to get api working on heroku but Im unable to create new user... I always got 404. Same for the localhost..

**Comment by diegohaz** [comment] 2018-03-10 17:59
Wich urls are you trying to access?

**Comment by maustand** [comment] 2018-03-11 08:01
@stychu  Could you give us more info  ?

Currently we are working in a full review of the code and fix some bugs that there were not fixed before...

So if it would be possible, let us to know the steps that you was doing in order to reproduce this problem.

Thanks !

**Comment by diegohaz** [comment] 2018-03-14 14:55
I'm closing this for now since the problem is probably related to #157, which was fixed in #160 and released as `v0.12`.

Let me know if the problem persists.

**Closed by diegohaz** 2018-03-14 14:55 UTC
Labels: needs more info
